# These are supported funding model platforms

github: 
patreon: ebankoff
open_collective: 
ko_fi: 
tidelift: 
community_bridge: 
liberapay:
issuehunt: 
otechie: 
lfx_crowdfunding: 
custom: https://qiwi.com/n/HERAMANT
